# services:
#   app:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: crm-backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/var/www
#     command: php artisan serve --host=0.0.0.0 --port=8000
#     environment:
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_DATABASE: crm
#       DB_USERNAME: crm_user
#       DB_PASSWORD: crm_pass
#     depends_on:
#       - db

#   db:
#     image: postgres:15
#     container_name: crm-postgres
#     environment:
#       POSTGRES_USER: crm_user
#       POSTGRES_PASSWORD: crm_pass
#       POSTGRES_DB: crm
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
  

# volumes:
#   postgres_data:


# services:
#   backend:
#     build: ./backend
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/var/www
#     working_dir: /var/www
#     command: php artisan serve --host=0.0.0.0 --port=8000
#     depends_on:
#       - db
#     environment:
#       DB_CONNECTION: pgsql
#       DB_HOST: db
#       DB_PORT: 5432
#       DB_DATABASE: crm
#       DB_USERNAME: crm_user
#       DB_PASSWORD: crm_pass


#   db:
#     image: postgres:15
#     ports:
#       - "5432:5432"
#     environment:
#       POSTGRES_DB: crm
#       POSTGRES_USER: crm_user
#       POSTGRES_PASSWORD: crm_pass
#     volumes:
#       - pgdata:/var/lib/postgresql/data

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./frontend:/app
#     stdin_open: true
#     tty: true
#     depends_on:
#       - backend

# volumes:
#   pgdata:


version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: crm-backend-new
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: crm
      DB_USERNAME: crm_user
      DB_PASSWORD: crm_pass
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: crm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: crm_user
      POSTGRES_PASSWORD: crm_pass
      POSTGRES_DB: crm
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    container_name: crm-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_data:



